
version: "3.8"
name: stress-worker
networks:
  app-shared:
    driver: bridge
  instaleap-rest_instaleap-rest-shared:
    external: true

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-stress-worker
    restart: always
    ports:
      - 5672:5672
      - 15675:15672
    volumes: 
      - ./rabbit-conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbit-conf/definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - app-shared
  app:
    container_name: app-stress-worker
    platform: linux/x86_64
    env_file:
      ../.env
    restart: always
    depends_on:
      - "rabbitmq"
    build:
      dockerfile: Dockerfile
      context: ../.
    ports:
      - "8287:8081"
    networks:
      - app-shared
      - instaleap-rest_instaleap-rest-shared